package com.example.server;

/**
 * Request payload used when creating a message.
 *
 * <p>The message identifier and creation timestamp are intentionally absent;
 * those values are generated by the server when the request is handled.</p>
 *
 * @param author   the message author
 * @param content  the message content
 * @param category the message category
 */
public record CreateMessageRequest(String author, String content, String category) {
}
