package com.example.server.dto;

/**
 * Client-supplied data required to create a message.
 *
 * <p>Identity and timestamp fields are intentionally excluded; they are
 * generated by the service layer. Field validation is also performed by the
 * service so all message-creation entry points use the same rules.</p>
 *
 * @param author   the message author
 * @param content  the message content
 * @param category the message category
 */
public record CreateMessageRequest(String author, String content, String category) {
}
