# تنظیمات پیش‌فرض Hibernate و سایر تنظیمات مربوط به Spring

# پورت سرور
server.port=9090

# تنظیمات Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/goldshop
spring.datasource.username=root
spring.datasource.password=password
