package com.example.server.model;

import java.util.UUID;

/**
 * Immutable representation of a message returned by the API.
 *
 * @param id unique identifier generated by the service
 * @param author message author
 * @param content message content
 * @param category required textual message category
 * @param timestamp creation timestamp generated by the service
 */
public record Message(
        UUID id,
        String author,
        String content,
        String category,
        long timestamp
) {
}
